### PR TITLE
Replace pthreads with pcntl_fork

### PR DESCRIPTION
**Pull request by BePsvPT**
一般的環境應該都支援 fork，這樣就不用額外安裝 pthreads extension

只有測試 rssMap.php 是否可以運作，articles.php 似乎有用到額外需要安裝的 extension

### CODE REVIEW

**Comment by pingyen** [comment]
感謝！以前我要 fork 出去大都用 shell_exec ，還真的沒看過 PHP 的 pcntl_fork 。

articles.php 不能跑是因為一進到 foreach 就卡在 while (pcntl_waitpid(0, $status) !== -1) 跑不出來。

但我大概知道怎麼改了！只缺時間 Q__Q ...

**Comment by peter279k** [comment]
推pcntl_fork! multi process is for Unix-based 系統

**Comment by pingyen** [comment]
Thanks. Finally, I did it.

**Comment by pingyen** [comment]
BTW, there is no PCNTL in Windows, but we have Ubuntu on Windows now.

**Comment by peter279k** [comment]
Wow....It's very sad about that.

**Comment by pingyen** [comment]
上面那句的意思是用 Ubuntu on Windows 就可以在 Windows 上用 PCNTL 了啊啊啊啊啊 XD

**Comment by peter279k** [comment]
I know that, but I don't like the Ubuntu on Windows

**Pull request closed without merging**
